// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// AddRefreshToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) AddRefreshToken(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for AddRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenService_AddRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRefreshToken'
type MockTokenService_AddRefreshToken_Call struct {
	*mock.Call
}

// AddRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenService_Expecter) AddRefreshToken(ctx any, token any) *MockTokenService_AddRefreshToken_Call {
	return &MockTokenService_AddRefreshToken_Call{Call: _e.mock.On("AddRefreshToken", ctx, token)}
}

func (_c *MockTokenService_AddRefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockTokenService_AddRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_AddRefreshToken_Call) Return(err error) *MockTokenService_AddRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenService_AddRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockTokenService_AddRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRefreshToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) DeleteRefreshToken(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenService_DeleteRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshToken'
type MockTokenService_DeleteRefreshToken_Call struct {
	*mock.Call
}

// DeleteRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenService_Expecter) DeleteRefreshToken(ctx any, token any) *MockTokenService_DeleteRefreshToken_Call {
	return &MockTokenService_DeleteRefreshToken_Call{Call: _e.mock.On("DeleteRefreshToken", ctx, token)}
}

func (_c *MockTokenService_DeleteRefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockTokenService_DeleteRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_DeleteRefreshToken_Call) Return(err error) *MockTokenService_DeleteRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenService_DeleteRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockTokenService_DeleteRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// IsTokenRevoked provides a mock function for the type MockTokenService
func (_mock *MockTokenService) IsTokenRevoked(ctx context.Context, token string) (bool, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for IsTokenRevoked")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_IsTokenRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTokenRevoked'
type MockTokenService_IsTokenRevoked_Call struct {
	*mock.Call
}

// IsTokenRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenService_Expecter) IsTokenRevoked(ctx any, token any) *MockTokenService_IsTokenRevoked_Call {
	return &MockTokenService_IsTokenRevoked_Call{Call: _e.mock.On("IsTokenRevoked", ctx, token)}
}

func (_c *MockTokenService_IsTokenRevoked_Call) Run(run func(ctx context.Context, token string)) *MockTokenService_IsTokenRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_IsTokenRevoked_Call) Return(b bool, err error) *MockTokenService_IsTokenRevoked_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTokenService_IsTokenRevoked_Call) RunAndReturn(run func(ctx context.Context, token string) (bool, error)) *MockTokenService_IsTokenRevoked_Call {
	_c.Call.Return(run)
	return _c
}
