// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	"auth-service/internal/auth/repositories/interfaces"
	"auth-service/internal/auth/transport/dto"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// AddRefreshToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) AddRefreshToken(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for AddRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenService_AddRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRefreshToken'
type MockTokenService_AddRefreshToken_Call struct {
	*mock.Call
}

// AddRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenService_Expecter) AddRefreshToken(ctx any, token any) *MockTokenService_AddRefreshToken_Call {
	return &MockTokenService_AddRefreshToken_Call{Call: _e.mock.On("AddRefreshToken", ctx, token)}
}

func (_c *MockTokenService_AddRefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockTokenService_AddRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_AddRefreshToken_Call) Return(err error) *MockTokenService_AddRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenService_AddRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockTokenService_AddRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRefreshToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) DeleteRefreshToken(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenService_DeleteRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshToken'
type MockTokenService_DeleteRefreshToken_Call struct {
	*mock.Call
}

// DeleteRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenService_Expecter) DeleteRefreshToken(ctx any, token any) *MockTokenService_DeleteRefreshToken_Call {
	return &MockTokenService_DeleteRefreshToken_Call{Call: _e.mock.On("DeleteRefreshToken", ctx, token)}
}

func (_c *MockTokenService_DeleteRefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockTokenService_DeleteRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_DeleteRefreshToken_Call) Return(err error) *MockTokenService_DeleteRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenService_DeleteRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockTokenService_DeleteRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// IsTokenRevoked provides a mock function for the type MockTokenService
func (_mock *MockTokenService) IsTokenRevoked(ctx context.Context, token string) (bool, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for IsTokenRevoked")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_IsTokenRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTokenRevoked'
type MockTokenService_IsTokenRevoked_Call struct {
	*mock.Call
}

// IsTokenRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenService_Expecter) IsTokenRevoked(ctx any, token any) *MockTokenService_IsTokenRevoked_Call {
	return &MockTokenService_IsTokenRevoked_Call{Call: _e.mock.On("IsTokenRevoked", ctx, token)}
}

func (_c *MockTokenService_IsTokenRevoked_Call) Run(run func(ctx context.Context, token string)) *MockTokenService_IsTokenRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_IsTokenRevoked_Call) Return(b bool, err error) *MockTokenService_IsTokenRevoked_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTokenService_IsTokenRevoked_Call) RunAndReturn(run func(ctx context.Context, token string) (bool, error)) *MockTokenService_IsTokenRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockUserService
func (_mock *MockUserService) Login(ctx context.Context, loginRequest dto.LoginRequest) (*interfaces.TokenPair, error) {
	ret := _mock.Called(ctx, loginRequest)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *interfaces.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.LoginRequest) (*interfaces.TokenPair, error)); ok {
		return returnFunc(ctx, loginRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.LoginRequest) *interfaces.TokenPair); ok {
		r0 = returnFunc(ctx, loginRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.LoginRequest) error); ok {
		r1 = returnFunc(ctx, loginRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockUserService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - loginRequest dto.LoginRequest
func (_e *MockUserService_Expecter) Login(ctx any, loginRequest any) *MockUserService_Login_Call {
	return &MockUserService_Login_Call{Call: _e.mock.On("Login", ctx, loginRequest)}
}

func (_c *MockUserService_Login_Call) Run(run func(ctx context.Context, loginRequest dto.LoginRequest)) *MockUserService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.LoginRequest
		if args[1] != nil {
			arg1 = args[1].(dto.LoginRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_Login_Call) Return(tokenPair *interfaces.TokenPair, err error) *MockUserService_Login_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockUserService_Login_Call) RunAndReturn(run func(ctx context.Context, loginRequest dto.LoginRequest) (*interfaces.TokenPair, error)) *MockUserService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockUserService
func (_mock *MockUserService) Logout(ctx context.Context, cookieValue string) error {
	ret := _mock.Called(ctx, cookieValue)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, cookieValue)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockUserService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - cookieValue string
func (_e *MockUserService_Expecter) Logout(ctx any, cookieValue any) *MockUserService_Logout_Call {
	return &MockUserService_Logout_Call{Call: _e.mock.On("Logout", ctx, cookieValue)}
}

func (_c *MockUserService_Logout_Call) Run(run func(ctx context.Context, cookieValue string)) *MockUserService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_Logout_Call) Return(err error) *MockUserService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_Logout_Call) RunAndReturn(run func(ctx context.Context, cookieValue string) error) *MockUserService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type MockUserService
func (_mock *MockUserService) Refresh(ctx context.Context, cookieValue string) (string, error) {
	ret := _mock.Called(ctx, cookieValue)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, cookieValue)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, cookieValue)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cookieValue)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockUserService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - cookieValue string
func (_e *MockUserService_Expecter) Refresh(ctx any, cookieValue any) *MockUserService_Refresh_Call {
	return &MockUserService_Refresh_Call{Call: _e.mock.On("Refresh", ctx, cookieValue)}
}

func (_c *MockUserService_Refresh_Call) Run(run func(ctx context.Context, cookieValue string)) *MockUserService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_Refresh_Call) Return(s string, err error) *MockUserService_Refresh_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserService_Refresh_Call) RunAndReturn(run func(ctx context.Context, cookieValue string) (string, error)) *MockUserService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockUserService
func (_mock *MockUserService) Register(ctx context.Context, loginRequest dto.LoginRequest) error {
	ret := _mock.Called(ctx, loginRequest)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.LoginRequest) error); ok {
		r0 = returnFunc(ctx, loginRequest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - loginRequest dto.LoginRequest
func (_e *MockUserService_Expecter) Register(ctx any, loginRequest any) *MockUserService_Register_Call {
	return &MockUserService_Register_Call{Call: _e.mock.On("Register", ctx, loginRequest)}
}

func (_c *MockUserService_Register_Call) Run(run func(ctx context.Context, loginRequest dto.LoginRequest)) *MockUserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.LoginRequest
		if args[1] != nil {
			arg1 = args[1].(dto.LoginRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_Register_Call) Return(err error) *MockUserService_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_Register_Call) RunAndReturn(run func(ctx context.Context, loginRequest dto.LoginRequest) error) *MockUserService_Register_Call {
	_c.Call.Return(run)
	return _c
}
