// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	"auth-service/core/domains"
	"auth-service/core/enums"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenManager creates a new instance of MockTokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenManager {
	mock := &MockTokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenManager is an autogenerated mock type for the TokenManager type
type MockTokenManager struct {
	mock.Mock
}

type MockTokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenManager) EXPECT() *MockTokenManager_Expecter {
	return &MockTokenManager_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) GenerateAccessToken(userID uuid.UUID, userRole enums.Role) (string, error) {
	ret := _mock.Called(userID, userRole)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, enums.Role) (string, error)); ok {
		return returnFunc(userID, userRole)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, enums.Role) string); ok {
		r0 = returnFunc(userID, userRole)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, enums.Role) error); ok {
		r1 = returnFunc(userID, userRole)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenManager_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockTokenManager_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - userID uuid.UUID
//   - userRole enums.Role
func (_e *MockTokenManager_Expecter) GenerateAccessToken(userID any, userRole any) *MockTokenManager_GenerateAccessToken_Call {
	return &MockTokenManager_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", userID, userRole)}
}

func (_c *MockTokenManager_GenerateAccessToken_Call) Run(run func(userID uuid.UUID, userRole enums.Role)) *MockTokenManager_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 enums.Role
		if args[1] != nil {
			arg1 = args[1].(enums.Role)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenManager_GenerateAccessToken_Call) Return(s string, err error) *MockTokenManager_GenerateAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenManager_GenerateAccessToken_Call) RunAndReturn(run func(userID uuid.UUID, userRole enums.Role) (string, error)) *MockTokenManager_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateTokenPair provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) GenerateTokenPair(userID uuid.UUID, userRole enums.Role) (*TokenPair, error) {
	ret := _mock.Called(userID, userRole)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokenPair")
	}

	var r0 *TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, enums.Role) (*TokenPair, error)); ok {
		return returnFunc(userID, userRole)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, enums.Role) *TokenPair); ok {
		r0 = returnFunc(userID, userRole)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, enums.Role) error); ok {
		r1 = returnFunc(userID, userRole)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenManager_GenerateTokenPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokenPair'
type MockTokenManager_GenerateTokenPair_Call struct {
	*mock.Call
}

// GenerateTokenPair is a helper method to define mock.On call
//   - userID uuid.UUID
//   - userRole enums.Role
func (_e *MockTokenManager_Expecter) GenerateTokenPair(userID any, userRole any) *MockTokenManager_GenerateTokenPair_Call {
	return &MockTokenManager_GenerateTokenPair_Call{Call: _e.mock.On("GenerateTokenPair", userID, userRole)}
}

func (_c *MockTokenManager_GenerateTokenPair_Call) Run(run func(userID uuid.UUID, userRole enums.Role)) *MockTokenManager_GenerateTokenPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 enums.Role
		if args[1] != nil {
			arg1 = args[1].(enums.Role)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenManager_GenerateTokenPair_Call) Return(tokenPair *TokenPair, err error) *MockTokenManager_GenerateTokenPair_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockTokenManager_GenerateTokenPair_Call) RunAndReturn(run func(userID uuid.UUID, userRole enums.Role) (*TokenPair, error)) *MockTokenManager_GenerateTokenPair_Call {
	_c.Call.Return(run)
	return _c
}

// IsAccessToken provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) IsAccessToken(claims *CustomClaims) bool {
	ret := _mock.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for IsAccessToken")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(*CustomClaims) bool); ok {
		r0 = returnFunc(claims)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTokenManager_IsAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAccessToken'
type MockTokenManager_IsAccessToken_Call struct {
	*mock.Call
}

// IsAccessToken is a helper method to define mock.On call
//   - claims *CustomClaims
func (_e *MockTokenManager_Expecter) IsAccessToken(claims any) *MockTokenManager_IsAccessToken_Call {
	return &MockTokenManager_IsAccessToken_Call{Call: _e.mock.On("IsAccessToken", claims)}
}

func (_c *MockTokenManager_IsAccessToken_Call) Run(run func(claims *CustomClaims)) *MockTokenManager_IsAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *CustomClaims
		if args[0] != nil {
			arg0 = args[0].(*CustomClaims)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenManager_IsAccessToken_Call) Return(b bool) *MockTokenManager_IsAccessToken_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTokenManager_IsAccessToken_Call) RunAndReturn(run func(claims *CustomClaims) bool) *MockTokenManager_IsAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// Parse provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) Parse(token string) (*CustomClaims, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *CustomClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*CustomClaims, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *CustomClaims); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CustomClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenManager_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockTokenManager_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - token string
func (_e *MockTokenManager_Expecter) Parse(token any) *MockTokenManager_Parse_Call {
	return &MockTokenManager_Parse_Call{Call: _e.mock.On("Parse", token)}
}

func (_c *MockTokenManager_Parse_Call) Run(run func(token string)) *MockTokenManager_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenManager_Parse_Call) Return(customClaims *CustomClaims, err error) *MockTokenManager_Parse_Call {
	_c.Call.Return(customClaims, err)
	return _c
}

func (_c *MockTokenManager_Parse_Call) RunAndReturn(run func(token string) (*CustomClaims, error)) *MockTokenManager_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRepository creates a new instance of MockTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepository {
	mock := &MockTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenRepository is an autogenerated mock type for the TokenRepository type
type MockTokenRepository struct {
	mock.Mock
}

type MockTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepository) EXPECT() *MockTokenRepository_Expecter {
	return &MockTokenRepository_Expecter{mock: &_m.Mock}
}

// AddRefreshToken provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) AddRefreshToken(ctx context.Context, tokenHash []byte) error {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for AddRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_AddRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRefreshToken'
type MockTokenRepository_AddRefreshToken_Call struct {
	*mock.Call
}

// AddRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash []byte
func (_e *MockTokenRepository_Expecter) AddRefreshToken(ctx any, tokenHash any) *MockTokenRepository_AddRefreshToken_Call {
	return &MockTokenRepository_AddRefreshToken_Call{Call: _e.mock.On("AddRefreshToken", ctx, tokenHash)}
}

func (_c *MockTokenRepository_AddRefreshToken_Call) Run(run func(ctx context.Context, tokenHash []byte)) *MockTokenRepository_AddRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_AddRefreshToken_Call) Return(err error) *MockTokenRepository_AddRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_AddRefreshToken_Call) RunAndReturn(run func(ctx context.Context, tokenHash []byte) error) *MockTokenRepository_AddRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRefreshToken provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) DeleteRefreshToken(ctx context.Context, tokenHash []byte) error {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenRepository_DeleteRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshToken'
type MockTokenRepository_DeleteRefreshToken_Call struct {
	*mock.Call
}

// DeleteRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash []byte
func (_e *MockTokenRepository_Expecter) DeleteRefreshToken(ctx any, tokenHash any) *MockTokenRepository_DeleteRefreshToken_Call {
	return &MockTokenRepository_DeleteRefreshToken_Call{Call: _e.mock.On("DeleteRefreshToken", ctx, tokenHash)}
}

func (_c *MockTokenRepository_DeleteRefreshToken_Call) Run(run func(ctx context.Context, tokenHash []byte)) *MockTokenRepository_DeleteRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_DeleteRefreshToken_Call) Return(err error) *MockTokenRepository_DeleteRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenRepository_DeleteRefreshToken_Call) RunAndReturn(run func(ctx context.Context, tokenHash []byte) error) *MockTokenRepository_DeleteRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshTokenByHash provides a mock function for the type MockTokenRepository
func (_mock *MockTokenRepository) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (domains.Token, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTokenByHash")
	}

	var r0 domains.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (domains.Token, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) domains.Token); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(domains.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenRepository_GetRefreshTokenByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshTokenByHash'
type MockTokenRepository_GetRefreshTokenByHash_Call struct {
	*mock.Call
}

// GetRefreshTokenByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash []byte
func (_e *MockTokenRepository_Expecter) GetRefreshTokenByHash(ctx any, tokenHash any) *MockTokenRepository_GetRefreshTokenByHash_Call {
	return &MockTokenRepository_GetRefreshTokenByHash_Call{Call: _e.mock.On("GetRefreshTokenByHash", ctx, tokenHash)}
}

func (_c *MockTokenRepository_GetRefreshTokenByHash_Call) Run(run func(ctx context.Context, tokenHash []byte)) *MockTokenRepository_GetRefreshTokenByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenRepository_GetRefreshTokenByHash_Call) Return(token domains.Token, err error) *MockTokenRepository_GetRefreshTokenByHash_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenRepository_GetRefreshTokenByHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash []byte) (domains.Token, error)) *MockTokenRepository_GetRefreshTokenByHash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// AddUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) AddUser(ctx context.Context, user domains.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domains.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_AddUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUser'
type MockUserRepository_AddUser_Call struct {
	*mock.Call
}

// AddUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domains.User
func (_e *MockUserRepository_Expecter) AddUser(ctx any, user any) *MockUserRepository_AddUser_Call {
	return &MockUserRepository_AddUser_Call{Call: _e.mock.On("AddUser", ctx, user)}
}

func (_c *MockUserRepository_AddUser_Call) Run(run func(ctx context.Context, user domains.User)) *MockUserRepository_AddUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domains.User
		if args[1] != nil {
			arg1 = args[1].(domains.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_AddUser_Call) Return(err error) *MockUserRepository_AddUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_AddUser_Call) RunAndReturn(run func(ctx context.Context, user domains.User) error) *MockUserRepository_AddUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserByID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) DeleteUserByID(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_DeleteUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserByID'
type MockUserRepository_DeleteUserByID_Call struct {
	*mock.Call
}

// DeleteUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserRepository_Expecter) DeleteUserByID(ctx any, userID any) *MockUserRepository_DeleteUserByID_Call {
	return &MockUserRepository_DeleteUserByID_Call{Call: _e.mock.On("DeleteUserByID", ctx, userID)}
}

func (_c *MockUserRepository_DeleteUserByID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserRepository_DeleteUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_DeleteUserByID_Call) Return(err error) *MockUserRepository_DeleteUserByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_DeleteUserByID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockUserRepository_DeleteUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserByID(ctx context.Context, userID uuid.UUID) (domains.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 domains.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domains.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domains.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(domains.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserRepository_Expecter) GetUserByID(ctx any, userID any) *MockUserRepository_GetUserByID_Call {
	return &MockUserRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *MockUserRepository_GetUserByID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) Return(user domains.User, err error) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (domains.User, error)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByNickname provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserByNickname(ctx context.Context, nickname string) (domains.User, error) {
	ret := _mock.Called(ctx, nickname)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByNickname")
	}

	var r0 domains.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domains.User, error)); ok {
		return returnFunc(ctx, nickname)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domains.User); ok {
		r0 = returnFunc(ctx, nickname)
	} else {
		r0 = ret.Get(0).(domains.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, nickname)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUserByNickname_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByNickname'
type MockUserRepository_GetUserByNickname_Call struct {
	*mock.Call
}

// GetUserByNickname is a helper method to define mock.On call
//   - ctx context.Context
//   - nickname string
func (_e *MockUserRepository_Expecter) GetUserByNickname(ctx any, nickname any) *MockUserRepository_GetUserByNickname_Call {
	return &MockUserRepository_GetUserByNickname_Call{Call: _e.mock.On("GetUserByNickname", ctx, nickname)}
}

func (_c *MockUserRepository_GetUserByNickname_Call) Run(run func(ctx context.Context, nickname string)) *MockUserRepository_GetUserByNickname_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUserByNickname_Call) Return(user domains.User, err error) *MockUserRepository_GetUserByNickname_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetUserByNickname_Call) RunAndReturn(run func(ctx context.Context, nickname string) (domains.User, error)) *MockUserRepository_GetUserByNickname_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) UpdateUser(ctx context.Context, user domains.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domains.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserRepository_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domains.User
func (_e *MockUserRepository_Expecter) UpdateUser(ctx any, user any) *MockUserRepository_UpdateUser_Call {
	return &MockUserRepository_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, user)}
}

func (_c *MockUserRepository_UpdateUser_Call) Run(run func(ctx context.Context, user domains.User)) *MockUserRepository_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domains.User
		if args[1] != nil {
			arg1 = args[1].(domains.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_UpdateUser_Call) Return(err error) *MockUserRepository_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, user domains.User) error) *MockUserRepository_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
